### ISSUE TITLE
Generator output creates both spaces and tabs

### ISSUE THREAD

**Issue by motowilliams** [pvantrepote/tstools#2]
Taking a chance as I see that tabs is mostly used in the project source but ...

**Comment by pvantrepote** [comment]
Good morning,

Thanks for your suggestion, but I have a question, are you using this vscode setting: editor.insertSpaces?

**Comment by pvantrepote** [comment]
Fixed y using user preferences to insert space vs tab.

**Comment by motowilliams** [comment]
I am using **editor.insertSpace** and also I have **editor.tabSize** set to **4**. It would be cool if that honored that value as well. Otherwise the indentation gets messed up unless the user happens to be using the same level you are.  Doing a document wide is a work around.

Great extension!!

**Comment by pvantrepote** [comment]
Sure, will add that to the next release.

**Comment by pvantrepote** [comment]
Hi Eric,

It is implemented in version 1.1.3 (published this morning).

Thanks,
Pascal.

**Comment by motowilliams** [comment]
le Awesome!  Great Work!
