### ISSUE TITLE
This is an error when I open vscode in extensionHost mode.

### ISSUE THREAD

**Issue by fallenleavesguy** [pvantrepote/tstools#4]
This is an error when I open vscode in extensionHost mode, just didn't open any path.
<img width="659" alt="screen shot 2016-07-29 at 7 53 01 pm" src="https://cloud.githubusercontent.com/assets/9261562/17247524/63cbc548-55c6-11e6-9793-b5d05b820a4b.png">

**Comment by pvantrepote** [comment]
Thanks for reporting this issue. 
I will look into it as soon as possible.

**Comment by pvantrepote** [comment]
Do you have the stack trace by chance, can't reproduce it :(

**Comment by fallenleavesguy** [comment]
you can fork or clone this minimal demo. https://github.com/yeluoqiuzhi/tstool-error-demo

**Comment by fallenleavesguy** [comment]
I used vscode-insider 1.4.0 and latest tstools

**Comment by pvantrepote** [comment]
Fixed in version 1.1.3
